---
#  Default run (maintenance release upgrade):
#
#  $ ansible-playbook -i inventory playbook_upgrade_single.yml
#  
#  Credits: Stephen Rivera
- hosts: firewall
  connection: local

  vars:
    device:
    # backup_config - Create a backup of the currently running config.
    backup_config: true

    # backup_filename - Filename for running config backup.
    backup_filename: '{{ inventory_hostname }}-{{ ansible_date_time.date }}.xml'

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Load Variables
      include_vars: host_vars/firewall.yml
    - name: Load PAN-OS Version
      include_vars: host_vars/panos_version.yml

    - name: Backup device config
      paloaltonetworks.panos.panos_op:
        provider: '{{ provider }}'
        cmd: 'save config to {{ backup_filename }}'
      when: backup_config|bool

    - name: Export configuration
      panos_export:
        provider: '{{ provider }}'
        category: 'configuration'
        filename: '{{ inventory_hostname }}-{{ ansible_date_time.date }}.xml'

    - name: Install target PAN-OS version
      paloaltonetworks.panos.panos_software:
        provider: '{{ provider }}'
        perform_software_check: true
        download: false
        version: '{{ version }}'
        restart: true

    - name: Pause for restart
      ansible.builtin.pause:
        seconds: 30

    - name: Check to see if device is ready
      paloaltonetworks.panos.panos_op:
        provider: '{{ provider }}'
        cmd: 'show chassis-ready'
      changed_when: false
      register: result
      until: result is not failed and (result.stdout | from_json).response.result == 'yes'
      retries: 30
      delay: 60
